proxy:
  title: My Awesome Shiny Portal
  port: 8080 # use Port 8080 for ShinyProxy
  
  container-wait-time: 30000 # how long should we wait for the container to spin up (30s as default as this is enough for our Shiny apps)
  heartbeat-rate: 10000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 60000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)

  usage-stats-url: http://ec2-3-83-107-112.compute-1.amazonaws.com:8086/write?db=shinyproxy_usagestats # use InfluxDB to store usage statistics; can be in a different server
  # usage-stats-username: xxxx # influxdb username if needed
  # usage-stats-password: xxxx # influxdb password if needed

  #### OpenID Connect Authentication ####
  authentication: openid # use openid auth framework
  openid:
    roles-claim: cognito:groups # use the groups value passed by AWS cognito to identify user groups 
    auth-url: https://test-databentobox.auth.us-east-1.amazoncognito.com/oauth2/authorize
    token-url: https://test-databentobox.auth.us-east-1.amazoncognito.com/oauth2/token
    jwks-url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_JpYhc28Wc/.well-known/jwks.json
    logout-url: https://test-databentobox.auth.us-east-1.amazoncognito.com/logout?client_id=vbrs7mjull4inb3rimhjrgdi1&logout_uri=test.databentobox.com
    client-id: vbrs7mjull4inb3rimhjrgdi1 # get this from AWS Cognito user pool management page
    client-secret: 12a6nsm442ololq018lj8hj0hvhuiai0mqaa6mqdq43f6sia0fen # get this from AWS Cognito user pool management page
  
  #### Simple Authentication ####
  # authentication: simple
  # admin-groups: admins
  # users:
  # - name: admin
  #   password: admin
  #   groups: admins
  
  docker:
      internal-networking: true
  
  # Below is a list of Shiny app and their config (including who can access to which)
  specs:
    - id: euler
      display-name: Euler's number
      container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
      container-image: presstofan/shiny-euler-app
      access-groups: admins
      container-network: sp-net

server:
  useForwardHeaders: true # this is very important to make the AWS Cognito auth works

logging:
  file:
    shinyproxy.log